
services:
  backend:
    build: ./backend
    container_name: imagens-backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: imagens-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgis/postgis:15-3.3
    container_name: imagens-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagens
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: imagens-redis
    ports:
      - "6379:6379"
